### ISSUE TITLE
Adding Support for Sprites

### ISSUE THREAD

**Issue by indikman** [shamsdev/davinci#11]
Does this support downloading images and replacing them in sprites?
I checked with the sprite renderer, it does apply to the material but not as a sprite

**Comment by indikman** [comment]
> Does this support downloading images and replacing them in sprites?
> I checked with the sprite renderer, it does apply to the material but not as a sprite

Added Sprite Loading support, Will load the sprite in its original size without fitting to a scale
[](https://github.com/shamsdev/davinci/pull/12)

**Comment by shamsdev** [comment]
#26 has been merged.
