### ISSUE TITLE
QUESTIONS

### ISSUE THREAD

**Issue by Techie-Pi** [shamsdev/davinci#2]
How to use it? Is there any wiki? Can I use it in my project without any problems?

**Comment by shamsdev** [comment]
Hello. Thanks for choosing Davinci.
It has a very simple usage. Just download and add main script located in [Assets/Davinci/Scripts/Davinci.cs](https://github.com/shamsdev/davinci/blob/master/Davinci/Assets/Davinci/Scripts/Davinci.cs) from this repository to your project, or simply download [Davinci-v1.1.unitypackage](https://github.com/shamsdev/davinci/blob/master/Davinci-v1.1.unitypackage) and open it. 
Now, you can call Davinci in any script of your project.
`Davinci.get().load(imageUrl).into(image).start();`
See [Examples](https://github.com/shamsdev/davinci/tree/master/Davinci/Assets/Davinci/Examples) for more information and sample codes.

**Comment by Techie-Pi** [comment]
Thanks @shamsdev ^^

**Comment by Techie-Pi** [comment]
Can I use it with a Texture2D?

**Comment by Techie-Pi** [comment]
How can I use it with a Material?
