### ISSUE TITLE
Community's opinion about creating a fork

### ISSUE THREAD

**Issue by Techie-Pi** [shamsdev/davinci#21]
There are some pull requests since november that have not been merged, and they include interesting things that are quite important, like #13 and #20 .
And I was thinking on creating a fork of davinci with all this features added and bugs fixed. I just wanted to know what the community thinks about this idea.
This, obviously, wouldn't be done if @shamsdev merges or comments on any PR or something like that.

**Comment by Techie-Pi** [comment]
Another option would be to move this repository to an organization or something similar and give write access to some maintainers and people willing to help with the project

**Comment by shamsdev** [comment]
Hello @Techie-Pi, Thank you for your comment. It's been a while I couldn't work on this project, but I have plans for this and new features will be added soon. Thank you again.
Regards.

**Comment by Techie-Pi** [comment]
Great! That's great to listen!
