### ISSUE TITLE
Create a .editorconfig file

### ISSUE THREAD

**Issue by Techie-Pi** [shamsdev/davinci#22]
After seeing the problems with #13 and #20 and the file changes that change nothing (probably end-of-line or something similar).
It may be an interesting idea to create a [.editorconfig file](https://editorconfig.org/), a file supported by [most IDEs without any plugin](https://editorconfig.org/#pre-installed) ([Visual Studio](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.0#coding-convention-support-through-editorconfig), [Rider](https://github.com/JetBrains/intellij-community/tree/master/plugins/editorconfig), Visual Studio Code [-with plugin-](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)...) to specify the charset, indent size and style, etc of certain files.

There could be also a [.gitattributes file](https://git-scm.com/docs/gitattributes), but that could interfere with Unity files.
I'll check the current coding styles and create a PR, although maybe @shamsdev prefers to set himself the coding style to be used in the project instead of a contributor*.

**Comment by shamsdev** [comment]
Thank you very much @Techie-Pi, that would be great! Can you please create that files?

**Comment by Techie-Pi** [comment]
Yes, of course

**Comment by Techie-Pi** [comment]
For both .editorconfig and .gitattributes I'm going to follow the [.NET code style rule options](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options).

The pull request will contain the following changes:
- .editorconfig and .gitattributes files
- all the files with the consistent end-of-line (will change really nothing but the EOLs)
- a workflow to check if the coding style is preserved (right now only checks for .editorconfig)

**Comment by shamsdev** [comment]
Very nice! Thank you @Techie-Pi

**Comment by Techie-Pi** [comment]
You're welcome!

**Comment by Techie-Pi** [comment]
#20 Closed, now #25
#13 is going to be remade by me
