### ISSUE TITLE
Material doesn't have a color property '_Color'

### ISSUE THREAD

**Issue by Techie-Pi** [shamsdev/davinci#4]
Material doesn't have a color property '_Color'
UnityEngine.Material:get_color()
<ImageLoader>d__39:MoveNext() (at Assets/Davinci/Davinci/Assets/Davinci/Scripts/Davinci.cs:416)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Davinci:loadSpriteToImage() (at Assets/Davinci/Davinci/Assets/Davinci/Scripts/Davinci.cs:372)
Davinci:start() (at Assets/Davinci/Davinci/Assets/Davinci/Scripts/Davinci.cs:306)
<DownloadImageURL>d__6:MoveNext() (at Assets/Scripts/DownloadImage.cs:51)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

This happens only with the setFadeTime.
`Davinci.get().load(url_download).setLoadingPlaceholder(loading_texture).into(materialRenderer).start();`

I will see the code and try to solve it   ;-)

>

**Comment by Techie-Pi** [comment]
Is my fault, sorry for open a lot of issues D:

**Comment by Techie-Pi** [comment]
Because I use a Mesh Renderer

**Comment by shamsdev** [comment]
No problem at all. It's always a pleasure. If you can improve the main script please send a PR and that makes me really happy :)

**Comment by Techie-Pi** [comment]
Ok! @shamsdev :-)
