### ISSUE TITLE
Loading version on Google Drive

### ISSUE THREAD

**Issue by rogiedodgie** [shamsdev/davinci#5]
I am not sure if this is an issue with Davinci. 
I have a program set up to load an image using a link from Google Drive (replacing 'open' with 'uc'). It loads up, but when I upload a new version of the image, and delete the old version using Manage Version, davinci loads up the original image.
Similarly, using Dropbox, I created a link and replaced the end with 'raw=1', and it loaded up fine. I replaced the Dropbox image with another image, and davinci loaded up the original.
When pasting the same link into a browser, I get the correct versions of the images.
Does davinci cache the image if it has already downloaded it or something, I can't figure out what I am doing wrong!
Thank you,
Roger

**Comment by shamsdev** [comment]
Hello :)
By default Davinci caches images from same urls. If you want to disable this feature, you can simply pass `False` through `setCached` function.
`Davinci.get().load(imageUrl).setCached(false).into(image).start();`
