### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by herbou** [shamsdev/davinci#9]
Is there any way to clear cached images? And thank you for this great tool 😊

**Comment by shamsdev** [comment]
Hello @herbou  😉
Thanks for using Davinci. 
Two static functions called `Davinci.ClearCache(imageUrl);` and `Davinci.ClearAllCachedFiles();` has beed added in d6a24106a4491edf7fb36e8439275be4ae590986
Take care!

**Comment by herbou** [comment]
That's cool 😊, thank you.
